package com.xfire.textlinker

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.Button
import android.widget.TextView
import androidx.fragment.app.Fragment
import androidx.fragment.app.activityViewModels
import androidx.navigation.fragment.findNavController
import androidx.navigation.fragment.navArgs

class SecondFragment : Fragment() {
    private val args: SecondFragmentArgs by navArgs()  // This should now be generated

    private lateinit var titleTextView: TextView
    private lateinit var contentTextView: TextView
    private lateinit var shareButton: Button
    
    // Shared ViewModel
    private val viewModel: NotesViewModel by activityViewModels()

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        return inflater.inflate(R.layout.fragment_second, container, false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        titleTextView = view.findViewById(R.id.tvDetailTitle)
        contentTextView = view.findViewById(R.id.tvDetailContent)
        shareButton = view.findViewById(R.id.btnShare)

        // Access the arguments generated by Safe Args
        titleTextView.text = args.title
        contentTextView.text = args.content
        
        // Set up share button
        shareButton.setOnClickListener {
            // Create a temporary note entity from the arguments
            val noteToShare = NoteEntity(
                id = 0, // Temporary ID
                title = args.title,
                content = args.content,
                timestamp = System.currentTimeMillis(),
                fromServer = false
            )
            
            // Set the selected note in the ViewModel
            viewModel.setSelectedNote(noteToShare)
            
            // Navigate to the ShareFragment with arguments
            val action = SecondFragmentDirections.actionSecondFragmentToShareFragment(
                noteId = noteToShare.id,
                noteTitle = noteToShare.title,
                noteContent = noteToShare.content
            )
            findNavController().navigate(action)
        }
    }
}
